version: '3.4'

services:
  samba:
    container_name: samba
    image: dperson/samba
    environment:
      TZ: 'Asia/Kolkata'
    networks:
      - default
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    read_only: true
    tmpfs:
      - /tmp
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - /home/ubuntu/:/drive
    command: 
      ' -s "share;/drive/share;yes;no;no" 
      -s "user1;/drive/user1;yes;no;no;user1"
      -s "user2;/drive/user2;yes;no;no;user2"
      -s "user3;/drive/user3;yes;no;no;user3"
      -u "user1;user1@pass"
      -u "user2;user2@pass"
      -u "user3,user3@pass" 
-g "follow symlinks = yes"
-g "wide links = yes"
-g "unix extensions = no"
-u "home;home@pass"
'

networks:
  default:
